const COMMAND_TYPE = {
  ACKNOWLEDGE: 0x01,
  CONNECT: 0x02,
  VERIFY_CONNECT: 0x03,
  DISCONNECT: 0x04,
  PING: 0x05,
  SEND_RELIABLE: 0x06,
  SEND_UNRELIABLE: 0x07,
  SEND_RELIABLE_FRAGMENT: 0x08
}

const MESSAGE_TYPE = {
  OPERATION_REQUEST: 0x02,
  OPERATION_RESPONSE: 0x03,
  EVENT_DATA_TYPE: 0x04,
  INTERNAL_OPERATION_REQUEST: 0x06,
  INTERNAL_OPERATION_RESPONSE: 0x07
}

module.exports = {
  COMMAND_TYPE,
  MESSAGE_TYPE
}
